language: node_js

node_js:
  - "0.8"
  - "0.10"
  - "0.11"

services:
  - redis-server
  - mongodb

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"

script: 'make test-cov'
after_success: 'make coveralls'

notifications:
  email:
    - updates@joo.la